[2023-10-02T21:38:58.963+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-02T21:38:44.185895+00:00 [queued]>
[2023-10-02T21:38:58.973+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-02T21:38:44.185895+00:00 [queued]>
[2023-10-02T21:38:58.974+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-02T21:38:58.974+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-02T21:38:58.974+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-02T21:38:58.988+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-10-02 21:38:44.185895+00:00
[2023-10-02T21:38:59.024+0000] {standard_task_runner.py:55} INFO - Started process 2935 to run task
[2023-10-02T21:38:59.030+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow-GitHub', 'build_save_model_task', 'manual__2023-10-02T21:38:44.185895+00:00', '--job-id', '344', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpt61bxqy3']
[2023-10-02T21:38:59.033+0000] {standard_task_runner.py:83} INFO - Job 344: Subtask build_save_model_task
[2023-10-02T21:38:59.124+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-02T21:38:44.185895+00:00 [running]> on host 4cbd71d73a25
[2023-10-02T21:38:59.262+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dheeraj
AIRFLOW_CTX_DAG_ID=Airflow-GitHub
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T21:38:44.185895+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-02T21:38:44.185895+00:00
[2023-10-02T21:38:59.437+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:1333: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-10-02T21:38:59.437+0000] {logging_mixin.py:137} INFO - Fitting 10 folds for each of 64 candidates, totalling 640 fits
[2023-10-02T21:39:03.189+0000] {logging_mixin.py:137} INFO - Best parameters: {'C': 0.6, 'class_weight': {1: 0.5, 0: 0.5}, 'penalty': 'l2', 'solver': 'saga'}
[2023-10-02T21:39:03.226+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-10-02T21:39:03.299+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=Airflow-GitHub, task_id=build_save_model_task, execution_date=20231002T213844, start_date=20231002T213858, end_date=20231002T213903
[2023-10-02T21:39:03.439+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-10-02T21:39:03.555+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
