[2023-10-02T20:59:58.141+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-02T20:59:49.516642+00:00 [queued]>
[2023-10-02T20:59:58.150+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-02T20:59:49.516642+00:00 [queued]>
[2023-10-02T20:59:58.151+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-02T20:59:58.151+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-02T20:59:58.151+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-02T20:59:58.163+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2023-10-02 20:59:49.516642+00:00
[2023-10-02T20:59:58.171+0000] {standard_task_runner.py:55} INFO - Started process 648 to run task
[2023-10-02T20:59:58.176+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow-GitHub', 'build_save_model_task', 'manual__2023-10-02T20:59:49.516642+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmpdo5d9qny']
[2023-10-02T20:59:58.178+0000] {standard_task_runner.py:83} INFO - Job 334: Subtask build_save_model_task
[2023-10-02T20:59:58.269+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow-GitHub.build_save_model_task manual__2023-10-02T20:59:49.516642+00:00 [running]> on host 4cbd71d73a25
[2023-10-02T20:59:58.366+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dheeraj
AIRFLOW_CTX_DAG_ID=Airflow-GitHub
AIRFLOW_CTX_TASK_ID=build_save_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T20:59:49.516642+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-02T20:59:49.516642+00:00
[2023-10-02T20:59:58.556+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:1333: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-10-02T20:59:58.557+0000] {logging_mixin.py:137} INFO - Fitting 10 folds for each of 64 candidates, totalling 640 fits
[2023-10-02T21:00:01.346+0000] {logging_mixin.py:137} INFO - Best parameters: {'C': 0.6, 'class_weight': {1: 0.5, 0: 0.5}, 'penalty': 'l2', 'solver': 'saga'}
[2023-10-02T21:00:01.356+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-10-02T21:00:01.392+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=Airflow-GitHub, task_id=build_save_model_task, execution_date=20231002T205949, start_date=20231002T205958, end_date=20231002T210001
[2023-10-02T21:00:01.459+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-10-02T21:00:01.622+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
